qcacmn: Remove qdf_exit_thread()
While migrating from v5.15 to v5.19 of the Linux Kernel, a build error
was observed:

ERROR: modpost: "do_exit" [...] undefined!

The reason do_exit is undefined is because Linux Kernel commit
eb55e716ac1a ("exit: Stop exporting do_exit") removed the
EXPORT_SYMBOL() with the justification "there are no more modular uses
of do_exit".

Commit eb55e716ac1a was preceded by commit 111e70490d2a
("exit/kthread: Have kernel threads return instead of calling
do_exit") which details why, since commit 63706172f332 ("kthreads:
rework kthread_stop()"), it is unnecessary to call do_exit().

Note that commit 63706172f332 was introduced in 2009 in v2.6.31-rc1.
Since we do not need to support any kernels before that time, we can
follow the same advice and return instead of calling do_exit().

Currently do_exit() is only called from qdf_exit_thread(). As a result
of the preceding investigation, all former callers of qdf_exit_thread()
have been modified to no longer call it.  Since it is obsolete, remove
it.

Change-Id: I22f27692fa8766df080630b9b0640c259285557c
CRs-Fixed: 3300460